/* eslint-disable */
/**
 * This file is auto-generated by Convex.
 * To regenerate, run `npx convex dev`.
 * For information on working with generated files, see the Convex docs.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as recommendations from "../recommendations.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  recommendations: typeof recommendations;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<"action" | "mutation" | "query", "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<"action" | "mutation" | "query", "internal">
>;
