/* eslint-disable */
/**
 * This file is auto-generated by Convex.
 * To regenerate, run `npx convex dev`.
 * For information on working with generated files, see the Convex docs.
 */

import { anyApi, type FunctionReference } from "convex/server";

type ApiType = {
  recommendations: {
    getPublicRecommendations: FunctionReference<"query">;
    getAllRecommendations: FunctionReference<"query">;
    addRecommendation: FunctionReference<"mutation">;
    deleteRecommendation: FunctionReference<"mutation">;
    setStaffPick: FunctionReference<"mutation">;
  };
  users: {
    getOrCreateUser: FunctionReference<"mutation">;
    getCurrentUser: FunctionReference<"query">;
  };
};

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = anyApi as unknown as ApiType;

export const internal = anyApi;
