/* eslint-disable */
/**
 * This file is auto-generated by Convex.
 * To regenerate, run `npx convex dev`.
 */

import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

/**
 * Define a query in this Convex app's public API.
 */
export const query = ((func: unknown) => func) as QueryBuilder<DataModel, "public">;

/**
 * Define a mutation in this Convex app's public API.
 */
export const mutation = ((func: unknown) => func) as MutationBuilder<DataModel, "public">;

/**
 * Define an action in this Convex app's public API.
 */
export const action = ((func: unknown) => func) as ActionBuilder<DataModel, "public">;

/**
 * Define an HTTP action.
 */
export const httpAction = ((func: unknown) => func) as HttpActionBuilder;

/**
 * A set of services for use within Convex query functions.
 */
export type QueryCtx = GenericQueryCtx<DataModel>;

/**
 * A set of services for use within Convex mutation functions.
 */
export type MutationCtx = GenericMutationCtx<DataModel>;

/**
 * A set of services for use within Convex action functions.
 */
export type ActionCtx = GenericActionCtx<DataModel>;

/**
 * An interface to read from the database within Convex query functions.
 */
export type DatabaseReader = GenericDatabaseReader<DataModel>;

/**
 * An interface to read from and write to the database within Convex mutation functions.
 */
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
